name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.13.0
        - name: Install
          run: npm install
        - name: Test
          env:
            SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
            SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
          run: npx wdio wdio.conf.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
